development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "taobaobao99@gmail.com"
  password: "taobaobao717"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "taobaobao99@gmail.com"
  password: "taobaobao717"
  enable_starttls_auto: true